apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eks-lab
  region: us-east-1
  version: "1.19"

vpc:
  subnets:
    private:
      us-east-1a: { id: subnet-05730b7d27bb99be8 }
      us-east-1b: { id: subnet-02507525d5f96dd1b }
      us-east-1c: { id: subnet-0d538db7901902f40 }
    public:
      us-east-1a: { id: subnet-042b1af2a9dc08651 }
      us-east-1b: { id: subnet-0651fd371912c23f9 }
      us-east-1c: { id: subnet-0774145cb73a0ec28 }     


nodeGroups:
  - name: nodegroup-1
    desiredCapacity: 3
    minSize: 1
    maxSize: 6
    instanceType: t3.small
    ami: ami-06c778c22c5e09bf7
    ssh:
      publicKeyPath: ~/.ssh/id_rsa.pub
      sourceSecurityGroupIds: ["sg-015b513c6f6cf9b1e"]
    privateNetworking: false
    tags:
      Project: eks-poc
      Environment: dev
  

cloudWatch:
  clusterLogging:
    enableTypes: ["audit", "authenticator", "scheduler", "controllerManager", "api"]
    
iam:
  withOIDC: true
  
