apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eks-poc-1-17-arm-public
  region: us-east-1
  version: "1.17"

vpc:
  subnets:
    private:
      us-east-1a: { id: subnet-0d2151f8697c5164b }
      us-east-1b: { id: subnet-093f8954fe4383a7c }
      us-east-1c: { id: subnet-00657c393e4bba645 }
    public:
      us-east-1a: { id: subnet-08b437b0f838c2b99 }
      us-east-1b: { id: subnet-0cd661bbf1aa8dcfa }
      us-east-1c: { id: subnet-0d67d81e705208018 }     


nodeGroups:
  - name: nodegroup-1
    desiredCapacity: 3
    instanceType: t3.small
    ssh:
      publicKeyPath: ~/.ssh/id_rsa.pub
    privateNetworking: true
    tags:
      Project: eks-poc
      Environment: dev
      
  - name: nodegroup-2
    desiredCapacity: 3
    instanceType: t4g.small
    ssh:
      publicKeyPath: ~/.ssh/id_rsa.pub
    #privateNetworking: true
    tags:
      Project: eks-poc
      Environment: dev
      
cloudWatch:
  clusterLogging:
    enableTypes: ["audit", "authenticator", "scheduler", "controllerManager", "api"]
    
iam:
  withOIDC: true
  
